name: Android APK Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'             # Set the Java version to 17
        distribution: 'adopt'          # Use AdoptOpenJDK

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip
        mkdir -p $HOME/android-sdk/cmdline-tools
        unzip commandlinetools-linux-8092744_latest.zip -d $HOME/android-sdk/cmdline-tools
        rm commandlinetools-linux-8092744_latest.zip
        yes | $HOME/android-sdk/cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-30" "build-tools;30.0.3"

    - name: Build APK
      run: |
        ./gradlew assembleDebug         # Run the Gradle build command directly from the top-level directory

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk            # Name of the artifact
        path: app/build/outputs/apk/debug/app-debug.apk  # Path to the generated APK
